import { AlertTriangle, RefreshCw, Sparkles, TrendingDown, TrendingUp } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { EmptyState } from '@/components/shared/EmptyState';
import { ErrorState } from '@/components/shared/ErrorState';
import { ConfidenceMeter } from './ConfidenceMeter';
import { ReportMarkdown } from './ReportMarkdown';
import { SourcesList } from './SourcesList';
import { APIError } from '@/lib/api/errors';
import { useRegenerateReport, useStockReport } from '@/features/report/useStockReport';
import { cn } from '@/lib/utils/cn';
import type { Recommendation, StockReport } from '@/lib/types';

const RECO_VARIANT: Record<Recommendation, 'success' | 'destructive' | 'secondary'> = {
  BUY: 'success',
  SELL: 'destructive',
  HOLD: 'secondary',
};

interface ReportCardProps {
  symbol: string;
}

export function ReportCard({ symbol }: ReportCardProps) {
  const { data, isLoading, isError, error, refetch } = useStockReport(symbol);
  const regen = useRegenerateReport(symbol);

  // 503 = LLM is not configured. Surface it as a first-class empty state.
  if (isError && error instanceof APIError && error.status === 503) {
    return (
      <EmptyState
        icon={Sparkles}
        title="LLM not configured"
        description="Set OPENROUTER_API_KEY in your .env and restart the API to unlock AI-generated reports."
      />
    );
  }

  if (isLoading) return <ReportSkeleton />;

  if (isError) {
    return (
      <ErrorState
        title="Couldn't load report"
        description={error instanceof Error ? error.message : undefined}
        onRetry={() => refetch()}
      />
    );
  }

  if (!data) return null;
  return (
    <ReportBody
      report={data}
      regenerating={regen.isPending}
      onRegenerate={() => regen.mutate()}
      regenError={regen.error instanceof Error ? regen.error.message : null}
    />
  );
}

function ReportBody({
  report,
  regenerating,
  onRegenerate,
  regenError,
}: {
  report: StockReport;
  regenerating: boolean;
  onRegenerate: () => void;
  regenError: string | null;
}) {
  return (
    <div className="space-y-4">
      {report.degraded && (
        <div className="flex items-start gap-3 rounded-md border border-[hsl(var(--warning))]/40 bg-[hsl(var(--warning))]/10 px-4 py-3 text-sm">
          <AlertTriangle className="mt-0.5 size-4 shrink-0 text-[hsl(var(--warning))]" />
          <div>
            <div className="font-medium text-foreground">Degraded report</div>
            <div className="text-muted-foreground">
              All LLM providers failed. This report contains a deterministic summary without AI
              narrative. Try regenerating.
            </div>
          </div>
        </div>
      )}

      <Card>
        <CardHeader className="flex flex-row items-start justify-between gap-4 space-y-0">
          <div className="space-y-1">
            <div className="flex flex-wrap items-center gap-2">
              <CardTitle className="text-base">LLM report</CardTitle>
              <Badge variant={RECO_VARIANT[report.recommendation]}>
                {report.recommendation === 'BUY' && <TrendingUp className="size-3" />}
                {report.recommendation === 'SELL' && <TrendingDown className="size-3" />}
                <span className="ml-1">{report.recommendation}</span>
              </Badge>
            </div>
            <CardDescription>
              {report.model_used ? (
                <>
                  Generated by <span className="font-medium">{report.model_used}</span>
                </>
              ) : (
                'Generated report'
              )}{' '}
              · {new Date(report.timestamp).toLocaleString()}
            </CardDescription>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={onRegenerate}
            disabled={regenerating}
          >
            <RefreshCw className={cn('size-4', regenerating && 'animate-spin')} />
            {regenerating ? 'Regenerating…' : 'Regenerate'}
          </Button>
        </CardHeader>
        <CardContent className="space-y-5">
          {regenError && (
            <p className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">
              Regenerate failed: {regenError}
            </p>
          )}

          <section>
            <ReportMarkdown>{report.summary}</ReportMarkdown>
          </section>

          {report.recommendation_rationale && (
            <section>
              <h4 className="mb-1.5 text-xs font-medium uppercase tracking-wide text-muted-foreground">
                Why this call
              </h4>
              <ReportMarkdown>{report.recommendation_rationale}</ReportMarkdown>
            </section>
          )}

          <div className="grid gap-5 md:grid-cols-2">
            <BulletSection
              title="Insights"
              items={report.insights}
              tone="ok"
              empty="No bullish factors identified."
            />
            <BulletSection
              title="Risks"
              items={report.risks}
              tone="down"
              empty="No risks identified."
            />
          </div>

          {report.news_impact && (
            <section>
              <h4 className="mb-1.5 text-xs font-medium uppercase tracking-wide text-muted-foreground">
                News impact
              </h4>
              <ReportMarkdown>{report.news_impact}</ReportMarkdown>
            </section>
          )}

          <ConfidenceMeter value={report.confidence} />

          {report.reasoning_chain.length > 0 && (
            <details className="rounded-md border bg-muted/20 p-3 text-sm [&_summary]:cursor-pointer">
              <summary className="font-medium">
                Reasoning chain ({report.reasoning_chain.length} steps)
              </summary>
              <ol className="mt-3 space-y-2 text-sm text-foreground/90">
                {report.reasoning_chain.map((step, i) => (
                  <li key={i} className="flex gap-3">
                    <span className="w-5 shrink-0 text-right text-muted-foreground tabular-nums">
                      {i + 1}.
                    </span>
                    <span>{step}</span>
                  </li>
                ))}
              </ol>
            </details>
          )}

          <SourcesList sources={report.sources} />
        </CardContent>
      </Card>
    </div>
  );
}

function BulletSection({
  title,
  items,
  tone,
  empty,
}: {
  title: string;
  items: string[];
  tone: 'ok' | 'down';
  empty: string;
}) {
  const bullet = {
    ok: 'bg-[hsl(var(--success))]',
    down: 'bg-destructive',
  }[tone];
  return (
    <section>
      <h4 className="mb-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">
        {title}
      </h4>
      {items.length === 0 ? (
        <p className="text-sm text-muted-foreground">{empty}</p>
      ) : (
        <ul className="space-y-2 text-sm">
          {items.map((item, i) => (
            <li key={i} className="flex items-start gap-2">
              <span className={cn('mt-1.5 size-1.5 shrink-0 rounded-full', bullet)} aria-hidden />
              <span>{item}</span>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

function ReportSkeleton() {
  return (
    <Card>
      <CardHeader>
        <Skeleton className="h-5 w-1/3" />
        <Skeleton className="h-4 w-1/2" />
      </CardHeader>
      <CardContent className="space-y-3">
        <Skeleton className="h-4 w-full" />
        <Skeleton className="h-4 w-[92%]" />
        <Skeleton className="h-4 w-[85%]" />
        <Skeleton className="h-32 w-full" />
        <Skeleton className="h-6 w-32" />
      </CardContent>
    </Card>
  );
}
